### ISSUE TITLE
No audio/response from API

### ISSUE THREAD

**Issue by RazaProdigy** [jhakulin/realtime-ai#1]
![image](https://github.com/user-attachments/assets/fd575fad-c3df-4f72-a3b0-d8dce5a62c88)

I keep seeing this error when i end my speech and there is no response from the API. Not sure what's wrong

**Comment by jhakulin** [comment]
Thanks for report! Tried reproduce, however works on my side. For some reason service does not respond successfully.
Do you see anything on ResponseDone event status_details field?
https://platform.openai.com/docs/api-reference/realtime-server-events/response/done

**Comment by jhakulin** [comment]
closing as no response

**Comment by Adesoji1** [comment]
wow, though nice work @jhakulin , in addition, could i contribute by addding pyproject.toml and dockerfile too for ease/
