### ISSUE TITLE
Awaiting a synchronous function

### ISSUE THREAD

**Issue by matthewgertner** [jhakulin/realtime-ai#17]
I noticed the following line in the async version of audio_stream_manager.py:

https://github.com/jhakulin/realtime-ai/blob/099e140a7c9419cd4c3c87dcb06bd363aedd0b95/src/realtime_ai/aio/audio_stream_manager.py#L42

Presumably this is just a bug. I guess you meant to use put(). Happy to file a PR if you agree.

Great work on this library BTW! Looks very promising.

**Comment by jhakulin** [comment]
Thank you for the report!

I agree it is a bug/oversight; you are very welcome to create PR.

I am making some additional changes soon so I can include the fix then also.
